# animation-1
- domain_lora_scale: 1.0
  adapter_lora_path: "models/DreamBooth_LoRA/v3_sd15_adapter.ckpt"
  dreambooth_path:   ""
  ipa_path: ""

  inference_config: "configs/inference/inference.yaml"
  motion_module:    "models/Motion_with_LoRA/character.ckpt"

  controlnet_config: "configs/inference/sparsectrl/latent_condition_32.yaml"
  controlnet_path:   "models/ReferenceNet/character.ckpt"

  # seed: 42
  steps: 50
  guidance_scale: 5

  controlnet_image_indexes: [7]
  controlnet_images:
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/0"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/1"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/2"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/3"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/4"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/5"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/6"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/7"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/8"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/9"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/10"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/11"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/12"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/13"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/14"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/15"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/16"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/17"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/18"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/19"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/20"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/21"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/22"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/23"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/24"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/25"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/26"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/27"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/28"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/29"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/30"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/31"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/32"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/33"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/34"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/35"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/36"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/37"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/38"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/39"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/Characterfulsketch_frames/40"
  controlnet_conditioning_scale: 1
  
  prompt:
    - "A portrait of a young woman with pale purple hair styled in a bob, adorned with a delicate headpiece and a serene expression."
    - "A girl with long, wavy hair in shades of pink and purple, looking slightly melancholic with her big, expressive eyes."
    - "A regal young woman with intricate hair ornaments and glowing yellow eyes, giving off a mystical and ethereal aura."
    - "A realistic painting of a young woman with dark hair, her gaze intense and focused, standing against a muted background."
    - "A girl with short, straight hair and a distant look in her eyes, her expression soft yet somewhat melancholic."
    - "A smiling young woman with long, dark hair and a gentle expression, her eyes sparkling with warmth."
    - "A woman with elaborate hair decorations and an elegant outfit, exuding grace and nobility with her poised demeanor."
    - "A girl with white hair styled in an updo, adorned with a delicate forehead ornament and a serene expression."
    - "A young woman with long, dark hair, looking thoughtfully to the side, her large eyes reflecting curiosity and innocence."
    - "A close-up of a girl with white hair, styled in an intricate updo, her expression calm and composed."
    - "A young woman with pale hair styled in two buns, wearing traditional attire and delicate earrings, exuding a calm presence."
    - "A girl with large, bright eyes and light hair, looking directly at the viewer with an innocent and curious expression."
    - "A realistic portrait of a young woman with wavy dark hair, her gaze direct and her expression thoughtful."
    - "A girl with white hair styled in two buns, wearing a school uniform and exuding a youthful charm."
    - "A woman with pale hair styled in a bob, adorned with a single earring, looking confidently at the viewer."
    - "A young woman with intricate braids and a serene expression, her bright blue eyes standing out."
    - "A young woman with dark hair and large eyes, smiling gently with a soft expression."
    - "A girl with long dark hair and a thoughtful look, her blue eyes reflecting a sense of wonder."
    - "A young woman with a soft smile and traditional attire, exuding grace and elegance."
    - "A girl with large blue eyes and short hair, wearing a school uniform and a cheerful expression."
    - "A young man with wavy dark hair and a serious expression, standing against a neutral background."
    - "A girl with purple hair styled in two buns, wearing a black outfit, her large eyes full of curiosity."
    - "A realistic portrait of a young woman with long dark hair and a soft expression, her gaze calm and steady."
    - "A girl with intricate purple hair and a gentle expression, adorned with delicate accessories."
    - "A woman with elegant, high-styled hair and a sophisticated look, wearing a black dress with jewelry."
    - "A young woman with a joyful expression, her hair adorned with colorful accessories, giving off a playful vibe."
    - "A young man with a cap, his expression thoughtful and his blue eyes sharp and focused."
    - "A woman with an elaborate hairstyle and a vibrant kimono, exuding an air of confidence and poise."
    - "A man with glasses and a bow tie, his expression serious and intellectual, standing against a muted background."
    - "A young woman with a colorful headscarf and traditional attire, her expression serene and composed."
    - "A stern-looking warrior with a rugged appearance, wearing traditional armor and a headband, exuding a sense of determination."
    - "A vibrant portrait of a young woman with striking purple hair and bright blue eyes, her expression confident and playful."
    - "A chef with a white hat and uniform, his expression serious and focused, ready to prepare a culinary masterpiece."
    - "A young man with dark hair and blue eyes, wearing a white and yellow outfit, his expression thoughtful and introspective."
    - "A military officer with a distinguished uniform and cap, exuding authority and leadership."
    - "A young man with glasses, holding a book and smiling warmly, giving off an intellectual vibe."
    - "A young woman adorned with a floral crown, her expression serene and her attire giving off a natural, earthy vibe."
    - "A young man with a green bow tie and a confident expression, dressed in a formal suit, exuding elegance and charm."
    - "A young woman with an elaborate updo and a gentle smile, wearing a blue and white dress, exuding grace and sophistication."
    - "A young woman with silver hair and an intricate outfit, her expression calm and composed, exuding an air of mystery."
    - "A young girl with large dark eyes and white hair styled in buns, wearing a blue and white outfit, exuding a sense of innocence and curiosity."
  n_prompt:
    - "worst quality, low quality, letterboxed"

  ddim: true
  sample_size: 512