# animation-1
- domain_lora_scale: 1.0
  adapter_lora_path: "models/DreamBooth_LoRA/v3_sd15_adapter.ckpt"
  dreambooth_path:   "models/DreamBooth_LoRA/revAnimated_v2Rebirth.safetensors"
  ipa_path: ""

  inference_config: "configs/inference/inference.yaml"
  motion_module:    "models/Motion_with_LoRA/speedpainting.ckpt"

  controlnet_config: "configs/inference/sparsectrl/latent_condition_32.yaml"
  controlnet_path:   "models/ReferenceNet/speedpainting.ckpt"

  # seed: 42
  steps: 50
  guidance_scale: 5

  controlnet_image_indexes: [7]
  controlnet_images:
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/0"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/1"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/2"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/3"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/4"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/5"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/6"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/7"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/8"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/9"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/10"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/11"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/12"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/13"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/14"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/15"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/16"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/17"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/18"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/19"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/20"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/21"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/22"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/23"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/24"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/25"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/26"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/27"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/28"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/29"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/30"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/31"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/32"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/33"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/34"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/35"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/36"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/37"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/38"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/39"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/40"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/41"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/42"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/43"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/44"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/45"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/46"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/47"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/48"
    - "/tiamat-NAS/nicolaus/siggraph24/data/lora/lora6_frames/49"
  controlnet_conditioning_scale: 1
  
  prompt:
    - "A bridge spans a river with a city skyline in the background"
    - "A wooden house in front of a field of flowers with green mountains in the distance"
    - "A blue vintage van parked on a grassy field with a village and mountains in the background"
    - "A mountain illuminated by moonlight and aurora at night with a silhouette of a person on the peak"
    - "A sunrise in a valley with sunlight shining through a rock arch"
    - "A wooden house in a snowy landscape illuminated by the setting sun"
    - "An ancient stone arch with a deer in front of ruins in the background"
    - "A green meadow leading to snow-capped mountains with a flock of birds in the sky"
    - "A giant rock standing in the blue sea"
    - "A sunset over a lake with the sun's reflection and mountains in the distance"
    - "A girl running on the beach at sunset with balloons in her hand"
    - "A dirt path leading through a lush forest with a mountain in the distance"
    - "A sunset over a marsh with tall grasses and a city skyline in the background"
    - "Two houses buried in snow in a winter forest landscape"
    - "A vast canyon with layered rock formations and a cloudy sky"
    - "A large cloud with a moon and a contrail in the sky"
    - "A wide green field with dramatic clouds forming in the sky"
    - "A rocky coastline with cliffs and turquoise water below"
    - "A snowy mountain range with jagged peaks under a clear sky"
    - "A woman in a red dress standing in a field with a large cloud in the background"
    - "A rocky landscape with green hills and a forest in the background"
    - "A sharp mountain peak illuminated by the setting sun"
    - "A wooden cabin in an autumn forest with mountains in the distance"
    - "Two girls standing on a rooftop with a bright blue sky and large clouds"
    - "A crescent moon in a field with a factory in the background during sunset"
    - "A monochromatic cityscape with tall towers and domes under a setting sun"
    - "A crashed plane in a desolate landscape"
    - "A white deer standing among tall trees with golden leaves"
    - "A sea cave with blue water and a sailboat visible through the opening"
    - "A camping setup with chairs and a canopy in a golden field with mountains in the background"
    - "A wooden boat on the water with seagulls perched on it"
    - "A sketch of a muscular man in a dynamic pose"
    - "A crushed soda can with a straw in it"
    - "A swan flapping its wings in the water"
    - "A glass of blue lemonade with slices of orange and ice cubes"
    - "A white goose walking on the grass near a pond"
    - "A green tea cake with flower decorations on a plate"
    - "A piece of toast with a fried egg on top"
    - "A yellow bell pepper"
    - "A cup of red tea with a heart-shaped reflection"
    - "A vast desert with dramatic clouds in the sky"
  n_prompt:
    - "worst quality, low quality, letterboxed"

  ddim: true
  sample_size: 512